In [71]:
# FUnction to encrypt a data file
keyfile = 'DataFiles/key.txt'
def dictionarykeyfile(keyfile):
    key = {}
    with open(keyfile, 'r') as f:
        for line in f:
            line = line.split()
            key[line[0]] = line[1]
    return key
dictionarykeyfile(keyfile)

    
def encryptMarksData(datafile,keyfile):
    # construct a dictionary for key data
    key = dictionarykeyfile(keyfile)
    with open(datafile, 'r') as f:
        filedata = f.read().split('\n')
    with open('DataFiles/encryptedMarks.txt','w') as f:
        for mark in filedata:
            line = ''
            for n in mark:
                line += key[n]
            f.write(line+'\n')
        return
import timeit
datafile = 'DataFiles/marks.txt' 
st =timeit.default_timer()
encryptMarksData(datafile,keyfile) 
print(timeit.default_timer()-st)

0.25902177799980564


In [70]:
def discryptdata(encryptedfile,keyfile):
    key = dictionarykeyfile(keyfile)
    newkey ={}
    for key,value in key.items():
        newkey[value] = key
        
    with open(encryptedfile,'r') as f:
        encryptedd ata = f.read().split('\n')
    with open('DataFiles/discryptedMarks.txt','w') as f:
        for encryptedmark in encrypteddata :
            line = ''
            for n in encryptedmark: 
                line += newkey[n]
            f.write(line+ '\n')
    return
encryptedfile = 'DataFiles/encryptedMarks.txt'
import timeit
st =timeit.default_timer()
discryptdata(encryptedfile,keyfile)
print(timeit.default_timer()-st)

0.006484444000307121


In [68]:
# Comprehension
keyfile = 'DataFiles/key.txt'
key = dictionarykeyfile(keyfile)
key

{'0': '4',
 '1': '5',
 '2': '6',
 '3': '7',
 '4': '8',
 '5': '9',
 '6': '0',
 '7': '1',
 '8': '2',
 '9': '3'}

In [23]:
# Comprehension
keyfile = 'DataFiles/key.txt'
key = dictionarykeyfile(keyfile)
evenkeys = {item for item in key.items() if int(item[0])%2 == 0}
evenkeys

{('0', '4'), ('2', '6'), ('4', '8'), ('6', '0'), ('8', '2')}

In [25]:
keyfile = 'DataFiles/key.txt'
key = dictionarykeyfile(keyfile)
evenkeys = {item for item in key if int(item[0])%2 == 0}
evenkeys

{'0', '2', '4', '6', '8'}

In [26]:
keyfile = 'DataFiles/key.txt'
key = dictionarykeyfile(keyfile)
evenkeys = {item for item in key}
evenkeys

{'0', '1', '2', '3', '4', '5', '6', '7', '8', '9'}

### Numpy Library
- To process N-Dimensional Arrays

In [28]:
import numpy as np
li = [1,2,3]
a = np.array(li)
a

array([1, 2, 3])

In [29]:
import numpy as np
li = [1,2,3]
a = np.array(li)
type(a)

numpy.ndarray

In [30]:
import numpy as np
li = [1,2,3,'z']
a = np.array(li)
type(a)

numpy.ndarray

In [31]:
import numpy as np
li = [1,2,3,'z']
a = np.array(li)
a

array(['1', '2', '3', 'z'], dtype='<U11')

In [34]:
import numpy as np
li = [1,2,3,'z']
a = np.array(li)
b =np.arange(15) # arange -> if a removed it shows error numpy has no range 
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
rn=np.random.randint(0,100,size = 10)
rn

array([77,  1, 78, 34, 41,  0, 15, 60, 27,  5])

In [35]:
import numpy as np
rn=np.random.randint(0,100,size = 10)
rn

array([ 2, 46, 58, 47, 18, 14, 64, 35,  6, 67])

In [40]:
## 3 dimenisional  arrays
rn=np.random.randint(0,2,size =(4,4))
rn

array([[1, 0, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 0, 0],
       [1, 0, 0, 1]])

In [41]:
rn=np.random.randint(0,2,size =(3,3))
rn

array([[1, 0, 0],
       [1, 0, 0],
       [1, 0, 0]])

In [42]:
rn=np.random.randint(0,2,size =(1,3))
rn

array([[0, 1, 1]])

In [43]:
rn=np.random.randint(0,2,size =(2,3))
rn

array([[0, 1, 1],
       [1, 1, 1]])

In [44]:
rn=np.random.randint(0,2,size =(6,3))
rn

array([[0, 1, 0],
       [0, 0, 0],
       [1, 0, 1],
       [1, 1, 0],
       [1, 0, 1],
       [1, 0, 1]])

In [45]:
rn=np.random.randint(0,2,size =(6,3))
rn[0][2]

1

In [49]:
rn=np.random.randint(0,2,size =(6,3,3))
rn

array([[[0, 1, 0],
        [1, 1, 0],
        [1, 0, 0]],

       [[0, 0, 1],
        [1, 0, 0],
        [0, 1, 1]],

       [[1, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 0, 1],
        [1, 1, 0],
        [0, 0, 1]],

       [[0, 1, 0],
        [1, 1, 1],
        [1, 1, 1]],

       [[0, 1, 1],
        [1, 1, 1],
        [1, 0, 0]]])

In [50]:
rn=np.random.randint(0,2,size =(6,3,3,5))
rn

array([[[[1, 1, 0, 1, 1],
         [1, 0, 1, 0, 1],
         [0, 0, 1, 1, 0]],

        [[1, 1, 1, 0, 1],
         [1, 0, 1, 1, 1],
         [0, 1, 0, 0, 1]],

        [[1, 1, 1, 1, 0],
         [0, 1, 1, 0, 0],
         [0, 0, 0, 0, 0]]],


       [[[0, 0, 0, 1, 0],
         [1, 0, 1, 0, 1],
         [0, 1, 1, 0, 1]],

        [[1, 1, 0, 0, 0],
         [0, 0, 0, 0, 0],
         [1, 0, 0, 0, 1]],

        [[0, 1, 0, 0, 0],
         [0, 1, 1, 1, 1],
         [0, 1, 1, 1, 1]]],


       [[[0, 1, 1, 1, 0],
         [0, 1, 0, 0, 0],
         [0, 0, 1, 1, 0]],

        [[0, 0, 1, 0, 0],
         [1, 0, 0, 0, 0],
         [1, 0, 0, 1, 1]],

        [[0, 1, 1, 1, 1],
         [1, 1, 0, 0, 1],
         [1, 1, 0, 0, 0]]],


       [[[1, 0, 1, 1, 0],
         [1, 1, 1, 1, 0],
         [1, 0, 1, 1, 0]],

        [[0, 1, 0, 0, 0],
         [0, 0, 0, 1, 1],
         [1, 1, 0, 1, 0]],

        [[1, 1, 0, 0, 1],
         [1, 1, 1, 0, 0],
         [0, 1, 0, 0, 1]]],


       [[[0, 0, 0, 1, 0],
      

In [54]:
rn=np.random.randint(0,2,size =(3,3,3,3))
rn[2][2][2][1]

0

In [58]:
rn.ndim
rn.size
rn.shape
rn.dtype
rn.itemsize
rn.nbytes

324

In [59]:
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [63]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [ ]:
import numpy as np
m =np.ones((3,3))
print(m)

### Pandas
use cases

- Data Cleaning
- Data Transformation
- Data Analysis

Notations

- Series
- DataFrames




In [72]:
import pandas as pd

internal1 ={'s1':21, 's2':18, 's3':24}
internal1 = pd.Series(internal1)
internal1

s1    21
s2    18
s3    24
dtype: int64

In [3]:
import pandas as pd

internal1 ={'s1':21, 's2':18, 's3':24}
internal1 = pd.Series(internal1)
internal2 ={'s1':15, 's2':18, 's3':12}
internal2 = pd.Series(internal2)
internal2

s1    15
s2    18
s3    12
dtype: int64

In [4]:
final = {'Internal1':internal1, 'Internal2':internal2}
final = pd.DataFrame(final)
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12

In [5]:
final.columns

Index(['Internal1', 'Internal2'], dtype='object')

In [6]:
final.values # list of all rows

array([[21, 15],
       [18, 18],
       [24, 12]], dtype=int64)

In [7]:
final.values[2]

array([24, 12], dtype=int64)

In [8]:
final.values[2,0]

24

In [9]:
for row in final.values:
    print('Internal1 - ',row[0],', Internal2 - ',row[1])

Internal1 -  21 , Internal2 -  15
Internal1 -  18 , Internal2 -  18
Internal1 -  24 , Internal2 -  12


In [11]:
final.loc[4] = [15, 18]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
3          15         18
4          15         18

In [12]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
4          15         18

In [14]:
final.drop(4)

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
3          15         18

In [15]:
final.drop(3)

Internal1  Internal2
s1         21         15
s2         18         18
s3         24         12
4          15         18

In [20]:
final.values[2] = [12,25]
final


Internal1  Internal2
s1         21         15
s2         18         18
s3         12         25

In [21]:
final.loc['s4'] = [17,19]
final

Internal1  Internal2
s1         21         15
s2         18         18
s3         12         25
s4         17         19

In [22]:
# Reading csv file data
import pandas as pd
filepath = 'DataFiles/Incometax.csv'
incomedf = pd.read_csv(filepath)
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [8]:
# Extract income of all states in 2003
import pandas as pd
filepath = 'DataFiles/Incometax.csv'
incomedf = pd.read_csv(filepath)
for row in  incomedf.values:
    print(row[1],':',row[-2])
        


Alabama : 43464
Alaska : 63648
Arizona : 47044
Arkansas : 39018
California : 57020


In [31]:
# Average income of Arizona
sum = 0
for i in range(2,11):
    sum = sum+incomedf.values[2][i]
sum/len(incomedf.values[2][2:])

47214.77777777778

In [32]:
sum = 0
for i in range(2,11):
    sum = sum+incomedf.values[2][i]
sum/9

47214.77777777778

In [36]:
sum = 0
for i in range(2,11):
    sum = sum+incomedf.values[2][i]
    print(sum/9, end ='')


5027.22222222222310211.33333333333415457.44444444444520670.1111111111125752.22222222222330962.8888888888936365.2222222222241592.33333333333647214.77777777778

In [39]:
sum = 0
for row in incomedf.values:
    sum = sum+row[-2]
print(sum/len(incomedf.values))
        

50038.8


In [9]:
# Acessing a unique value based on row, column informaation
# Income of state in a given year 
import pandas as pd
filepath = 'DataFiles/Incometax.csv'
incomedf = pd.read_csv(filepath)
def getRandowIndex(df, rowkey):
    for i in range(len(df.values)):
        if df.values[i][0] == rowkey or df.values[i][1] == columnkey:
            rowindex=i
def valueFromRowColumn(df,rowkey, columnkey):
    rowindex = getRowIndex(df, rowkey)
    for i in range(len(df.values)):
        if df.values[i][0] == rowkey or df.values[i][1] == columnkey:
            rowindex=i
    for i in range(len(df.columns)):
        if df.columns[i]== columnkey:
            columnindex=i
    return df.values[rowindex][columnindex]
valueFromRowColumn(incomedf,'04000US06', '2009')    

56134

In [11]:
# Function to update data based on rowkey
import pandas as pd
filepath = 'DataFiles/Incometax.csv'
incomedf = pd.read_csv(filepath)
def getRowIndex(df, rowkey):
    for i in range(len(df.values)):
        if df.values[i][0] == rowkey or df.values[i][1] == columnkey:
            rowindex=i
def getColumnIndex(df, columnkey):
    for i in range(len(df.columns)):
        if df.columns[i]== columnkey:
            columnindex=i
def valueFromRowColumn(df,rowkey, columnkey):
    rowindex = getRowIndex(df, rowkey)
    for i in range(len(df.values)):
        if df.values[i][0] == rowkey or df.values[i][1] == columnkey:
            rowindex=i
    for i in range(len(df.columns)):
        if df.columns[i]== columnkey:
            columnindex=i
    return df.values[rowindex][columnindex]
valueFromRowColumn(incomedf,'04000US06', '2009') 

NameError: name 'columnkey' is not defined

In [ ]:
def updateDataFromRowColumn(df, rowkey, columnkey):
    rowindex = getRowIndex(df, rowkey)
    columnkey = getColumnIndex(df, columnkey)
    row = df.values[rowindex]
    row[columnindex] = newdata
    df.loc[rowindex] =row
    return
updateDataFromRowColumn(incomedf, 'Arizona', '2007',columnkey)
incomedf

In [13]:
# Function to write data frame to csv
incomedf.to_csv(filepath, index = 'false')
incomedf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  47215  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [17]:
# Function to addd a new row of data to dataframe
def addRowdataFrame(df, rowdata):
    lastrowindex =len(df.values)-1
    df.loc[lastrowindex+1] = rowdata
    return
rowdata = [1,2,3,4,56,7,8,9,10,78,0]
addRowdataFrame(incomedf,rowdata )
